name: GitHub Actions Test
on: [push]

jobs:
  my-first-jon:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello world"
      - name: runpython
        run: |
          pip install -r requirements.txt
          python ci.py
      
